"""Remove annotated thumbnail

Revision ID: 26bd644759e6
Revises: 7a16064c7514
Create Date: 2026-06-11 17:46:34.368035

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "26bd644759e6"
down_revision = "7a16064c7514"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("annotation_sessions_image_id_fkey"),
        "annotation_sessions",
        type_="foreignkey",
    )
    op.alter_column(
        "annotation_sessions",
        "image_id",
        new_column_name="oxygenator_image_id",
    )
    op.create_foreign_key(
        "annotation_sessions_oxygenator_image_id_fkey",
        "annotation_sessions",
        "oxygenator_images",
        ["oxygenator_image_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("oxygenator_images", "thumbnail_annotated")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "oxygenator_images",
        sa.Column(
            "thumbnail_annotated",
            sa.LargeBinary(),
            nullable=True,
        ),
    )
    op.drop_constraint("annotation_sessions_oxygenator_image_id_fkey", "annotation_sessions", type_="foreignkey")
    op.alter_column(
        "annotation_sessions",
        "oxygenator_image_id",
        new_column_name="image_id",
    )
    op.create_foreign_key(
        op.f("annotation_sessions_image_id_fkey"),
        "annotation_sessions",
        "oxygenator_images",
        ["image_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
