"""Remove image filename

Revision ID: 9611d188a74e
Revises: 26bd644759e6
Create Date: 2026-06-12 06:18:02.758765

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "9611d188a74e"
down_revision = "26bd644759e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("oxygenator_images", "filename")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "oxygenator_images",
        sa.Column("filename", sa.String(), nullable=False),
    )
    # ### end Alembic commands ###
