"""Remove mimetype

Revision ID: ffd752db3e23
Revises: cd47d1b19a12
Create Date: 2026-06-30 19:48:05.489024

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "ffd752db3e23"
down_revision = "cd47d1b19a12"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("oxygenator_images", "mimetype")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "oxygenator_images",
        sa.Column("mimetype", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
