"""Add thumbnail_annotated back

Revision ID: 0e43b2d4c858
Revises: 9611d188a74e
Create Date: 2026-06-12 21:18:53.325783

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0e43b2d4c858"
down_revision = "9611d188a74e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "oxygenator_images",
        sa.Column("thumbnail_annotated", sa.LargeBinary(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("oxygenator_images", "thumbnail_annotated")
    # ### end Alembic commands ###
