"""add breakdown of thrombus types

Revision ID: 2d6974341913
Revises: 3f73cb2b7590
Create Date: 2026-05-28 01:58:22.361434

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "2d6974341913"
down_revision = "3f73cb2b7590"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "annotation_sessions", sa.Column("clot_area", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column(
        "annotation_sessions", sa.Column("fibrin_area", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column(
        "annotation_sessions", sa.Column("total_area", sa.Integer(), nullable=False, server_default="0")
    )
    op.drop_column("annotation_sessions", "area")
    op.add_column(
        "images", sa.Column("thumbnail_annotated", sa.LargeBinary(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("images", "thumbnail_annotated")
    op.add_column(
        "annotation_sessions",
        sa.Column("area", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("annotation_sessions", "total_area")
    op.drop_column("annotation_sessions", "fibrin_area")
    op.drop_column("annotation_sessions", "clot_area")
    # ### end Alembic commands ###
