"""Add ECMO model

Revision ID: 345e88d150dd
Revises:
Create Date: 2026-04-05 06:20:08.938100

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "345e88d150dd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.create_table(
    #     "ecmo",
    #     sa.Column("id", sa.Uuid(), nullable=False),
    #     sa.Column("name", sa.String(), nullable=False),
    #     sa.Column("created_at", sa.DateTime(), nullable=False),
    #     sa.PrimaryKeyConstraint("id"),
    #     sa.UniqueConstraint("name"),
    # )
    # op.create_table(
    #     "image",
    #     sa.Column("id", sa.Uuid(), nullable=False),
    #     sa.Column("ecmo_id", sa.Uuid(), nullable=False),
    #     sa.Column("file_key", sa.String(), nullable=False),
    #     sa.Column("width_px", sa.Integer(), nullable=False),
    #     sa.Column("height_px", sa.Integer(), nullable=False),
    #     sa.Column("width_mm", sa.Float(), nullable=False),
    #     sa.Column("height_mm", sa.Float(), nullable=False),
    #     sa.Column("created_at", sa.DateTime(), nullable=False),
    #     sa.ForeignKeyConstraint(
    #         ["ecmo_id"],
    #         ["ecmo.id"],
    #     ),
    #     sa.PrimaryKeyConstraint("id"),
    # )
    # op.create_table(
    #     "annotation",
    #     sa.Column("id", sa.Uuid(), nullable=False),
    #     sa.Column("image_id", sa.Uuid(), nullable=False),
    #     sa.Column("area_px", sa.Float(), nullable=False),
    #     sa.Column("created_at", sa.DateTime(), nullable=False),
    #     sa.ForeignKeyConstraint(
    #         ["image_id"],
    #         ["image.id"],
    #     ),
    #     sa.PrimaryKeyConstraint("id"),
    # )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table("annotation")
    # op.drop_table("image")
    op.drop_table("ecmo")
    # ### end Alembic commands ###
