"""Add undo column

Revision ID: 3f73cb2b7590
Revises: df2b3b9dabfb
Create Date: 2026-05-22 16:19:24.563080

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3f73cb2b7590"
down_revision = "df2b3b9dabfb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("segmentations", sa.Column("undo", sa.Boolean(), nullable=False, server_default="false"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("segmentations", "undo")
    # ### end Alembic commands ###
