"""Make thumbnail nullable

Revision ID: 4c1a5365143b
Revises: ffd752db3e23
Create Date: 2026-06-30 19:55:31.724281

"""

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4c1a5365143b"
down_revision = "ffd752db3e23"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "oxygenator_images",
        "thumbnail",
        existing_type=postgresql.BYTEA(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "oxygenator_images",
        "thumbnail",
        existing_type=postgresql.BYTEA(),
        nullable=False,
    )
    # ### end Alembic commands ###
