"""Add thumbnail to images

Revision ID: 6475014aacbf
Revises: a38eb165c9db
Create Date: 2026-05-20 06:03:49.466906

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "6475014aacbf"
down_revision = "a38eb165c9db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("images", sa.Column("thumbnail", sa.LargeBinary(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("images", "thumbnail")
    # ### end Alembic commands ###
