"""Add initial tables

Revision ID: 7a16064c7514
Revises:
Create Date: 2026-06-09 21:53:35.415242

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7a16064c7514"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oxygenators",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "type", sa.Enum("HLS", "NAUTILUS", name="oxygenatortype"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("object_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "oxygenator_images",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("oxygenator_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("mimetype", sa.String(), nullable=False),
        sa.Column("original", sa.LargeBinary(), nullable=False),
        sa.Column("thumbnail", sa.LargeBinary(), nullable=False),
        sa.Column("thumbnail_annotated", sa.LargeBinary(), nullable=True),
        sa.Column("cropped", sa.LargeBinary(), nullable=False),
        sa.Column("width_original", sa.Integer(), nullable=False),
        sa.Column("height_original", sa.Integer(), nullable=False),
        sa.Column("width_cropped", sa.Integer(), nullable=False),
        sa.Column("height_cropped", sa.Integer(), nullable=False),
        sa.Column("mm2_per_pixel", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["oxygenator_id"], ["oxygenators.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "annotation_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("image_id", sa.Uuid(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("mask", sa.LargeBinary(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("clot_area", sa.Integer(), nullable=False),
        sa.Column("fibrin_area", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["image_id"], ["oxygenator_images.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "annotations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("annotation_session_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("CLOT", "FIBRIN", "ERASE", name="annotationtype"),
            nullable=False,
        ),
        sa.Column("path", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("mask", sa.LargeBinary(), nullable=False),
        sa.Column("clot_area", sa.Integer(), nullable=False),
        sa.Column("fibrin_area", sa.Integer(), nullable=False),
        sa.Column("undo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["annotation_session_id"], ["annotation_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("annotations")
    op.drop_table("annotation_sessions")
    op.drop_table("oxygenator_images")
    op.drop_table("users")
    op.drop_table("oxygenators")
    # ### end Alembic commands ###
