"""Add type to ecmos

Revision ID: a38eb165c9db
Revises: cbda6f68a788
Create Date: 2026-05-15 05:08:46.022362

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a38eb165c9db"
down_revision = "cbda6f68a788"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE ecmotype AS ENUM ('GETINGE', 'NAUTILUS')")
    op.add_column(
        "ecmo",
        sa.Column(
            "type", sa.Enum("GETINGE", "NAUTILUS", name="ecmotype"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ecmo", "type")
    op.execute("DROP TYPE ecmotype")
    # ### end Alembic commands ###
