"""Change to JSONB

Revision ID: b43340f37569
Revises: e4b88a8af614
Create Date: 2026-05-21 23:55:37.222581

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b43340f37569"
down_revision = "e4b88a8af614"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column("segmentations", "path")
    # op.add_column(
    #     "segmentations",
    #     sa.Column("path", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    # )
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column(
    #     "segmentations",
    #     "path",
    #     existing_type=postgresql.JSONB(astext_type=sa.Text()),
    #     type_=postgresql.ARRAY(sa.INTEGER()),
    #     existing_nullable=False,
    # )
    # op.drop_column("segmentations", "path")
    # op.execute("ALTER TYPE thrombustype RENAME TO thrombustype_old")
    # op.execute("CREATE TYPE thrombustype AS ENUM ('CLOT', 'FIBRIN')")
    # op.drop_column("segmentations", "thrombus_type")
    op.add_column(
        "segmentations",
        sa.Column(
            "thrombus_type",
            sa.Enum("CLOT", "FIBRIN", name="thrombustype"),
            nullable=False,
        ),
    )
    # op.execute("DROP TYPE thrombustype_old")
    # ### end Alembic commands ###
