"""Add annotation_sessions mask

Revision ID: cbda6f68a788
Revises: d0b0d1ba4eaf
Create Date: 2026-05-13 05:00:47.734096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbda6f68a788'
down_revision = 'd0b0d1ba4eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_sessions', sa.Column('mask', sa.LargeBinary(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotation_sessions', 'mask')
    # ### end Alembic commands ###