"""Make cropped image nullable

Revision ID: cd47d1b19a12
Revises: 0e43b2d4c858
Create Date: 2026-06-30 05:01:57.122359

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cd47d1b19a12"
down_revision = "0e43b2d4c858"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "oxygenator_images", "cropped", existing_type=postgresql.BYTEA(), nullable=True
    )
    op.alter_column(
        "oxygenator_images", "width_cropped", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "oxygenator_images", "height_cropped", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "oxygenator_images",
        "mm2_per_pixel",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "oxygenator_images",
        "mm2_per_pixel",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "oxygenator_images",
        "height_cropped",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "oxygenator_images", "width_cropped", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "oxygenator_images", "cropped", existing_type=postgresql.BYTEA(), nullable=False
    )
    # ### end Alembic commands ###
