"""change clot/fibrin area tracking

Revision ID: cf013285778a
Revises: 2d6974341913
Create Date: 2026-05-29 04:43:03.042147

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cf013285778a"
down_revision = "2d6974341913"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("segmentations", sa.Column("clot_area", sa.Integer(), nullable=False, server_default="0"))
    op.add_column(
        "segmentations", sa.Column("fibrin_area", sa.Integer(), nullable=False, server_default="0")
    )
    op.execute("ALTER TYPE thrombustype ADD VALUE 'ERASE'")
    op.drop_column("segmentations", "area")
    op.drop_column("segmentations", "prompt_type")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "segmentations",
        sa.Column(
            "prompt_type",
            postgresql.ENUM("CIRCLE", "POINT", name="prompttype"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "segmentations",
        sa.Column("area", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "segmentations",
        "thrombus_type",
        existing_type=sa.Enum("CLOT", "FIBRIN", "ERASE", name="annotationtype"),
        type_=postgresql.ENUM("CLOT", "FIBRIN", name="thrombustype"),
        existing_nullable=False,
    )
    op.drop_column("segmentations", "fibrin_area")
    op.drop_column("segmentations", "clot_area")
    # ### end Alembic commands ###
