"""change to float

Revision ID: d0b0d1ba4eaf
Revises: 2ebfbc3adb1f
Create Date: 2026-05-11 01:28:10.112984

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d0b0d1ba4eaf"
down_revision = "2ebfbc3adb1f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE prompttype AS ENUM ('CIRCLE', 'POINT')")
    op.add_column(
        "segmentations",
        sa.Column(
            "prompt_type", sa.Enum("CIRCLE", "POINT", name="prompttype"), nullable=False
        ),
    )
    op.execute("CREATE TYPE thrombustype AS ENUM ('CLOT', 'FIBRIN')")
    op.add_column(
        "segmentations",
        sa.Column(
            "thrombus_type",
            sa.Enum("CLOT", "FIBRIN", name="thrombustype"),
            nullable=False,
        ),
    )
    op.add_column("segmentations", sa.Column("area", sa.Integer(), nullable=False))
    op.alter_column(
        "segmentations",
        "x1",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "segmentations",
        "y1",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "segmentations",
        "x2",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "segmentations",
        "y2",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.drop_column("segmentations", "type")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "segmentations",
        sa.Column(
            "type",
            postgresql.ENUM("CIRCLE", "POINT", name="segmentationtype"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "segmentations",
        "y2",
        existing_type=sa.Integer(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "segmentations",
        "x2",
        existing_type=sa.Integer(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "segmentations",
        "y1",
        existing_type=sa.Integer(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "segmentations",
        "x1",
        existing_type=sa.Integer(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.drop_column("segmentations", "area")
    op.drop_column("segmentations", "thrombus_type")
    op.drop_column("segmentations", "prompt_type")
    # ### end Alembic commands ###
