"""Modify image model

Revision ID: de61e0f846af
Revises: 395da5810b4f
Create Date: 2026-05-10 20:10:55.867069

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "de61e0f846af"
down_revision = "395da5810b4f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "images",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ecmo_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("mimetype", sa.String(), nullable=False),
        sa.Column("original", sa.LargeBinary(), nullable=False),
        sa.Column("cropped", sa.LargeBinary(), nullable=False),
        sa.Column("width_original", sa.Integer(), nullable=False),
        sa.Column("height_original", sa.Integer(), nullable=False),
        sa.Column("width_cropped", sa.Integer(), nullable=False),
        sa.Column("height_cropped", sa.Integer(), nullable=False),
        sa.Column("mm2_per_pixel", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ecmo_id"],
            ["ecmo.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "annotation_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("image_id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["images.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "segmentations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("annotation_session_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type", sa.Enum("CIRCLE", "POINT", name="segmentationtype"), nullable=False
        ),
        sa.Column("x1", sa.Float(), nullable=False),
        sa.Column("y1", sa.Float(), nullable=False),
        sa.Column("x2", sa.Float(), nullable=True),
        sa.Column("y2", sa.Float(), nullable=True),
        sa.Column("mask", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["annotation_session_id"],
            ["annotation_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("annotation")
    op.drop_table("image")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("ecmo_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("filename", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "original_data", postgresql.BYTEA(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "cropped_data", postgresql.BYTEA(), autoincrement=False, nullable=False
        ),
        sa.Column("width_px", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("height_px", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "mm2_per_p2",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["ecmo_id"], ["ecmo.id"], name=op.f("image_ecmo_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("image_pkey")),
    )
    op.create_table(
        "annotation",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("image_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "area_px",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["image_id"], ["image.id"], name=op.f("annotation_image_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("annotation_pkey")),
    )
    op.drop_table("segmentations")
    op.drop_table("annotation_sessions")
    op.drop_table("images")
    # ### end Alembic commands ###
