"""add area to annotation_sessions

Revision ID: df2b3b9dabfb
Revises: b43340f37569
Create Date: 2026-05-22 03:46:30.039045

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "df2b3b9dabfb"
down_revision = "b43340f37569"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "annotation_sessions", sa.Column("area", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("annotation_sessions", "area")
    # ### end Alembic commands ###
