"""Change to raw path

Revision ID: e4b88a8af614
Revises: 6475014aacbf
Create Date: 2026-05-21 23:21:27.907734

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "e4b88a8af614"
down_revision = "6475014aacbf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "segmentations",
        sa.Column("path", sa.ARRAY(sa.Integer(), dimensions=2), nullable=False),
    )
    op.drop_column("segmentations", "y2")
    op.drop_column("segmentations", "x1")
    op.drop_column("segmentations", "x2")
    op.drop_column("segmentations", "y1")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "segmentations",
        sa.Column("y1", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "segmentations",
        sa.Column("x2", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "segmentations",
        sa.Column("x1", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "segmentations",
        sa.Column("y2", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("segmentations", "path")
    # ### end Alembic commands ###
